api/urls.py
from django.urls import path, include

from rest_framework import routers

from knox import views as knox_views

from . import views


router= routers.DefaultRouter()
router.register('emp', views.apiEMP)
router.register('category', views.apiCategory)
router.register('product', views.apiProduct)
router.register('account', views.apiAccount)
router.register('permission', views.apiPermission)
router.register('user', views.apiUser)
router.register('info', views.apiInfoEMP, basename='infoemp')
router.register('order', views.apiOrder)
router.register('orderdetail', views.apiOrderDetail)
# router.register('orderemp', views.apiOrderEmp, basename='orderemp')


# app_name= 'emp'

urlpatterns = [

    path('', include(router.urls)),

    #register
    path('register/', views.RegisterAPI.as_view(), name='api-register'),
    path('login/', views.LoginAPI.as_view(), name='api-login'),
    path('logout/', knox_views.LogoutView.as_view(), name='api-logout'),
    # path('logoutall/', knox_views.LogoutAllView.as_view(), name='api-logoutall'),

    path('infouser/<email>', views.api_getInfoEmp, name='info'),

    # path('orderemp/<id>', views.api_getOrderEmp, name='orderemp'),

    path('a/', views.api_getAllEmp, name='apiemp'),
    # path('create', views.api_createEmp, name='create'),
    
    path('<id>/', views.api_getIDEmp, name='empID'),   
    path('update/<id>/', views.api_updateEmp, name='update-emp'),
    # path('delete/<id>/', views.api_delEmp, name='delete'),
    
    

]

djchicken/urls.py
from django.contrib import admin
from django.urls import path, include

from account.views import logoutUser


urlpatterns = [
    path('admin/', admin.site.urls), 
    
    # web
    path('', include('core.urls')),
    path('emp/', include('emp.urls')),
    path('product/', include('product.urls')),
    path('account/', include('account.urls')),
    path('order/', include('order.urls')),

    path('logout/', logoutUser, name='logout'),

    # api
    path('api/', include('api.urls')),
    
]

emp/urls.py
from django.urls import path, include

from rest_framework import routers

from . import views
# from .views import GetAllEMPAPIView, GetAllEMPViewSet

# router= routers.DefaultRouter()
# router.register('api-1', views.GetAllEMPViewSet)

urlpatterns = [
    # path('api/', include(router.urls)),

    # path('api/', views.GetAllEMPAPIView.as_view(), name='empapi'),


    path('', views.getAllEMP, name='emp'),
    path('add/', views.addEMP, name='addemp'),
    path('del/<id>', views.delEMP, name='delemp'),
    path('update/<id>', views.updateEMP, name='updateemp'),
   

    
]

emp/models.py
from email.policy import default
from random import choices

from django.db import models
from account.models import Account

# Create your models here.

class EMPs(models.Model):

    genders= (
        ('other', 'Other'),
        ('male', 'Male'),
        ('female', 'Female'),
    )

    id = models.AutoField(primary_key=True)
    l_name = models.CharField(max_length= 15)
    f_name= models.CharField(max_length= 15)
    gender= models.CharField(max_length= 6, choices= genders, default= 'male')
    date= models.DateField(default= '2001-01-01') # yyyy-mm-dd
    numberPhone= models.IntegerField()
    address= models.CharField(max_length= 30)
    salary= models.FloatField(default= 0)
    # id_account= models.ForeignKey(Account, on_delete=models.SET_NULL, null=True,blank=True)
    email= models.EmailField(max_length= 50, unique= True)
    status= models.BooleanField(default= True)

    def __str__(self):
        return str(self.id)

emp/forms.py
from django import forms

from .models import EMPs


class CreateEMPPostForm(forms.ModelForm):

	class Meta:
		model = EMPs
		fields = { 'id','l_name', 'f_name', 'gender', 'date','numberPhone','address', 'salary','email' }
		
		

emp/views.py
from argparse import Action
from urllib import response
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.contrib import messages

from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status, permissions, viewsets

import requests
import json

from .models import EMPs
from .forms import CreateEMPPostForm



# Create your views here.


def getAllEMP(request):

    url_api= requests.get('https://apichicken.herokuapp.com/api/emp/')
    context = url_api.json()

    return render(request, 'homepage/emp/EMP.html', {
        'emps': context
        })


def addEMP(request):

    url_api_account= requests.get('https://apichicken.herokuapp.com/api/account/')
    account_ = url_api_account.json()

    url_api= 'https://apichicken.herokuapp.com/api/emp/'
    # context = url_api.json()
    data={}     
    
    form= CreateEMPPostForm(request.POST or None)
    if form.is_valid():
        form.save()
        
        

    data['l_name']= form.data.get('l_name')
    data['f_name']= form.data.get('f_name')
    data['gender']= form.data.get('gender')
    data['date']= form.data.get('date')
    data['address']= form.data.get('address')
    data['numberPhone']= form.data.get('numberPhone')
    data['salary']= form.data.get('salary')
    data['email']= form.data.get('email')
    data['status']= form.data.get('status')
  
    # print(data)


    requests.post(url_api, data=data)


    
    return render(request, 'homepage/emp/addEMP.html', {

        'account':account_

    })


def delEMP(request, id):

    url_api= 'https://apichicken.herokuapp.com/api/emp/%s' %id
    # url_api= 'https://apichicken.herokuapp.com/api/delete/%s' %id
    # context = url_api.json()
    data={}     

    form= CreateEMPPostForm(request.POST or None)
    if form.is_valid():
        form.save()

    data['l_name']= form.data.get('l_name')
    data['f_name']= form.data.get('f_name')
    data['gender']= form.data.get('gender')
    data['date']= form.data.get('date')
    data['address']= form.data.get('address')
    data['numberPhone']= form.data.get('numberPhone')
    data['salary']= form.data.get('salary')
    data['email']= form.data.get('email')
    data['status']= form.data.get('status')

    # print(data)
    
    requests.delete(url_api, data=data)

    return redirect('/emp')



def updateEMP(request, id):

    url_api_account= requests.get('https://apichicken.herokuapp.com/api/account/')
    account_ = url_api_account.json()

    url_api= 'https://apichicken.herokuapp.com/api/emp/%s' %id
    url_get='https://apichicken.herokuapp.com/api/%s/' %id

    info_emp= requests.get(url_get)
    context = info_emp.json()

    data={}     

    form= CreateEMPPostForm(request.POST or None )
    if form.is_valid():
        form.save()

    data['l_name']= form.data.get('l_name')
    data['f_name']= form.data.get('f_name')
    data['gender']= form.data.get('gender')
    data['date']= form.data.get('date')
    data['address']= form.data.get('address')
    data['numberPhone']= form.data.get('numberPhone')
    data['salary']= form.data.get('salary')
    data['email']= form.data.get('email')
    data['status']= form.data.get('status')

    print(data)
    
    requests.patch(url_api, data=data)

    return render(request, 'homepage/emp/updateEMP.html', {

        'emp': context,
        'account': account_
        
        })

templates/homepage/emp/addEMP.html
{% extends 'homepage/base.html' %}
{% load static %}


{% block cssblock %}
    <!-- Custom fonts for this template-->
    <link href="{% static 'homepage/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static 'homepage/css/sb-admin-2.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this page -->
    <link href="{% static 'homepage/vendor/datatables/dataTables.bootstrap4.min.css' %}" rel="stylesheet">

{% endblock %}

{% block content1 %}
<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

{% endblock %}

    {% block content2 %}

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>

                    <!-- Topbar Search -->
                    <form
                        class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
                        <div class="input-group">
                            <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..."
                                aria-label="Search" aria-describedby="basic-addon2">
                            <div class="input-group-append">
                                <button class="btn btn-primary" type="button">
                                    <i class="fas fa-search fa-sm"></i>
                                </button>
                            </div>
                        </div>
                    </form>

                    {% endblock %}
        
                    
                    
                    {% block content3 %}

                </nav>
                <!-- End of Topbar -->

                <!-- Begin Page Content -->
                <div class="container-fluid">

                    <!-- Page Heading -->
                    <div class="col-lg-7">
                        <div class="p-5">
                            <div class="text-center">
                                <h1 class="h4 text-gray-900 mb-4">Nhập thông tin nhân viên mới!</h1>
                            </div>

                          

                            <form action="{% url 'addemp' %}"  method="post">
                                {% csrf_token %}

                                <div class="form-group row">
                                    <div class="col-sm-6 mb-3 mb-sm-0">
                                        <input type="text" class="form-control form-control-user" name="f_name" id="id_f_name"
                                            placeholder="First Name">
                                    </div>
                                    <div class="col-sm-6">
                                        <input type="text" class="form-control form-control-user" name="l_name" id="id_l_name"
                                            placeholder="Last Name">
                                    </div>
                                </div>
                                    <div class="form-group row">
                                        <div class="col-sm-6 mb-3 mb-sm-0" name="gender">
                                        <label>Giới tính: </label>

                                        <ul>
                                            <input type="radio" name="gender" value="other" data-parsley- 
                                                multiple="gender" checked> Other</input>
                                            <input type="radio" name="gender" value="male" data-parsley- 
                                                multiple="gender"> Male</input>
                                            <input type="radio" name="gender" value="female" data-parsley- 
                                                multiple="gender"> Female</input>
                                        </ul>
                                        
                                    </div>
                                    <div class="col-sm-6">
                                        <label for="ns">Ngày sinh:</label> 
                                        <input type="date" class="form-control form-control-user" name="date" id="id_gt"
                                                placeholder="Ngày sinh">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <input type="text" class="form-control form-control-user" name="address" id="id_address"
                                        placeholder="Địa chỉ">
                                </div>
                                <div class="form-group row">
                                    <div class="col-sm-6 mb-3 mb-sm-0">
                                        <input type="number" class="form-control form-control-user" id="id_nb"
                                        name="numberPhone" placeholder="Số điện thoại">
                                    </div>
                                    <div class="col-sm-6">
                                        <input type="number" class="form-control form-control-user" id="id_salary"
                                        name="salary" placeholder="Lương">
                                    </div>
                                </div>
                                
                                <div class="form-group ">
                                    <input type="email" class="form-control form-control-user" name="email"
                                        placeholder="Email">

                                </div>

                                <div class="form-group row">
                                    <div class="col-sm-6 mb-3 mb-sm-0" name="gender">
                                    <label>Trạng thái: </label>

                                    <ul>
                                        <input type="radio" name="status" value="True" data-parsley- 
                                            multiple="status" checked> True </input>
                                        <input type="radio" name="status" value="False" data-parsley- 
                                            multiple="status"> False</input>
                                    </ul>
                                    
                                </div>
                            </div>
                                

                                <button type="submit" class="btn btn-primary btn-user btn-block">
                                    Thêm
                                </button>
                                <a href="/emp" class="btn bg-gray-200 btn-user btn-block">
                                    Trở lại
                                </a>
                                <hr>
                                
                            </form>
                            <hr>
                            <!-- {% for message in messages %}

                            <p id="messages">{{ message }}</p>

                        {% endfor %} -->
                        </div>
                    </div>

                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->

            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; Your Website 2020</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

   
    {% endblock %}


{% block jsblock %}

    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'homepage/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'homepage/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'homepage/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'homepage/js/sb-admin-2.min.js' %}"></script>

    <!-- Page level plugins -->
    <script src="{% static 'homepage/vendor/datatables/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'homepage/vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>

    <!-- Page level custom scripts -->
    <script src="{% static 'homepage/js/demo/datatables-demo.js' %}"></script>

{% endblock %}

templates/homepage/emp/updateEMP.html
{% extends 'homepage/base.html' %}
{% load static %}


{% block cssblock %}
    <!-- Custom fonts for this template-->
    <link href="{% static 'homepage/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static 'homepage/css/sb-admin-2.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this page -->
    <link href="{% static 'homepage/vendor/datatables/dataTables.bootstrap4.min.css' %}" rel="stylesheet">

{% endblock %}

{% block content1 %}
<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

{% endblock %}

    {% block content2 %}

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>

                    <!-- Topbar Search -->
                    <form
                        class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
                        <div class="input-group">
                            <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..."
                                aria-label="Search" aria-describedby="basic-addon2">
                            <div class="input-group-append">
                                <button class="btn btn-primary" type="button">
                                    <i class="fas fa-search fa-sm"></i>
                                </button>
                            </div>
                        </div>
                    </form>

                    {% endblock %}
        
                    
                    
                    {% block content3 %}

                </nav>
                <!-- End of Topbar -->

                <!-- Begin Page Content -->
                <div class="row justify-content-center">

                    <!-- Page Heading -->
                    <div class="col-lg-7">
                        <div class="p-5">
                            <div class="text-center">
                                <h1 class="h4 text-gray-900 mb-4">Chỉnh sửa thông tin nhân viên</h1>
                            </div>
                            <form action="{% url 'updateemp' emp.id %}" method="post">
                                {% csrf_token %}    
                                
                                <div class="form-group row">
                                    <div class="col-sm-6 mb-3 mb-sm-0">
                                        <input type="text" class="form-control form-control-user" name="f_name" id="id_f_name"
                                            placeholder="First Name" value= '{{ emp.f_name }}'>
                                    </div>
                                    <div class="col-sm-6">
                                        <input type="text" class="form-control form-control-user" name="l_name" id="id_l_name"
                                            placeholder="Last Name" value= '{{ emp.l_name }}'>
                                    </div>
                                </div>
                                    <div class="form-group row">
                                        <div class="col-sm-6 mb-3 mb-sm-0" name="gender">
                                        <label>Giới tính: </label>

                                        <ul>
                                            <input type="radio" name="gender" value="other" data-parsley- 
                                                multiple="gender" checked> Other</input>
                                            <input type="radio" name="gender" value="male" data-parsley- 
                                                multiple="gender"> Male</input>
                                            <input type="radio" name="gender" value="female" data-parsley- 
                                                multiple="gender"> Female</input>
                                        </ul>
                                        
                                    </div>
                                    <div class="col-sm-6">
                                        <label for="ns">Ngày sinh:</label> 
                                        <input type="date" class="form-control form-control-user" name="date" id="id_gt"
                                                placeholder="Ngày sinh" value= '{{ emp.date }}'>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <input type="text" class="form-control form-control-user" name="address" id="id_address"
                                        placeholder="Địa chỉ" value= '{{ emp.address }}'>
                                </div>
                                <div class="form-group row">
                                    <div class="col-sm-6 mb-3 mb-sm-0">
                                        <input type="number" class="form-control form-control-user" id="id_nb"
                                        name="numberPhone" placeholder="Số điện thoại" value= '{{ emp.numberPhone }}'>
                                    </div>
                                    <div class="col-sm-6">
                                        <input type="number" class="form-control form-control-user" id="id_salary"
                                        name="salary" placeholder="Lương" value= '{{ emp.salary }}'>
                                    </div>
                                </div>
                                
                                <div class="form-group ">
                                    <input type="email" class="form-control form-control-user" name="email"
                                        placeholder="Email">

                                </div>

                                <div class="form-group row">
                                    <div class="col-sm-6 mb-3 mb-sm-0" name="gender">
                                    <label>Trạng thái: </label>

                                    <ul>
                                        <input type="radio" name="status" value="True" data-parsley- 
                                            multiple="status" checked> True </input>
                                        <input type="radio" name="status" value="False" data-parsley- 
                                            multiple="status"> False</input>
                                    </ul>
                                    
                                </div>
                            </div>

                               <button type="submit" class="btn btn-primary btn-user btn-block">
                                    Lưu
                                </button>
                                <a href="/emp" class="btn bg-gray-200 btn-user btn-block">
                                    Trở lại
                                </a>
                                <hr>
                                
                            </form>
                            <hr>

                        </div>
                    </div>

                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->

            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; Your Website 2020</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    
    {% endblock %}


{% block jsblock %}

    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'homepage/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'homepage/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'homepage/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'homepage/js/sb-admin-2.min.js' %}"></script>

    <!-- Page level plugins -->
    <script src="{% static 'homepage/vendor/datatables/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'homepage/vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>

    <!-- Page level custom scripts -->
    <script src="{% static 'homepage/js/demo/datatables-demo.js' %}"></script>

{% endblock %}